---
title: "ValenciaR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ValenciaR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ValenciaR) # devtools::install_github("lasy/ValenciaR")
library(ggplot2)
library(phyloseq)
library(magrittr)
library(dplyr)
```



```{r}

valencia_centroids <- get_Valencia_clusters()
pseudo_valencia_tax_table <- 
  build_Valencia_tax_table(taxa_vec = colnames(valencia_centroids))

```


```{r}

# data from "Replication and Refinement of a Vaginal Microbial Signature of Preterm Birth", Callahan, 2017
data("example_data") 

set.seed(1)
random_samples <- sample(example_data@sam_data$SampleID, 100)
example_data <- example_data %>% subset_samples(SampleID %in% random_samples)
input <- example_data@otu_table %>% as.matrix()
tax_table <- 
  example_data@tax_table %>% 
  as.data.frame() %>% 
  set_rownames(1:nrow(example_data@tax_table)) %>% 
  mutate(Domain = Kingdom)

res <- convert_to_Valencia_taxonomy(input = input, tax_table = tax_table)
CSTs <- assign_to_Valencia_clusters(res$converted_input, distance = "BC")

ggplot(CSTs$assignment, aes(x = subCST, fill = CST)) +
  geom_bar() +
  facet_grid(. ~ CST, scales = "free", space = "free") +
  ylab("Number of samples") +
  guides(fill = "none")

```

